crud_app/urls.py
from django.urls import path
from .import views

app_name = 'crud_app'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('list/', views.SchoolList.as_view(), name='list'),
    path('detail/<int:pk>/', views.SchoolDetail.as_view(), name='detail'),
    path('update/<int:pk>/', views.SchoolUpdate.as_view(), name='update'),
    path('create/', views.SchoolCreate.as_view(), name='create'),
    path('delete/<int:pk>/', views.SchoolDelete.as_view(), name='delete'),
]

crud_base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_app.urls'))
]

crud_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
  name = models.CharField(max_length=200)
  principal = models.CharField(max_length=200)
  location = models.CharField(max_length=200)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('crud_app:detail', kwargs={'pk':self.pk})


class Student(models.Model):
  name = models.CharField(max_length=200)
  age = models.IntegerField()
  school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='student')

  def __str__(self):
    return self.name

crud_app/views.py
from django.shortcuts import render
from crud_app.models import School
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView

# Create your views here.
class Index(TemplateView):
  template_name = 'crud_app/index.html'

class SchoolList(ListView):
  model = School

class SchoolDetail(DetailView):
  model = School

class SchoolUpdate(UpdateView):
  model = School
  fields = '__all__'

class SchoolCreate(CreateView):
  model = School
  fields = '__all__'

class SchoolDelete(DeleteView):
  model = School
  context_object_name = 'school_delete'
  success_url = reverse_lazy('crud_app:list')

crud_app/templates/crud_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Latest compiled and minified CSS -->
 <!--  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous"> -->
 <link rel="stylesheet" type="text/css" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
  <title>Crud_App</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'crud_app:index' %}">Home</a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'crud_app:list' %}">Schools</a>
      </li>


    </ul>
  </div>

</nav>
<div class="container">

{% block content %}
{% endblock content %}

</div>



</body>
</html>

crud_app/templates/crud_app/index.html
{% extends 'crud_app/base.html' %}

{% block content %}


<div class="container">
	<div class="jumbotron">

		<h1>Welcome</h1>
		
	</div>
	
</div>

{% endblock content %}

crud_app/templates/crud_app/school_confirm_delete.html
{% extends 'crud_app/base.html' %}



{% block content %}

<div class="container jumbotron">

<h1>Are you sure you want to delete {{school_delete.name}}</h1>

<form method="POST">
	{% csrf_token %}
	<p><input class="btn btn-danger" type="submit" value="Confirm"></p>
	<p><a class="btn btn-warning" href="{% url 'crud_app:detail' school_delete.id %}">Cancel</a></p>
</form>


</div>

{% endblock content %}

crud_app/templates/crud_app/school_detail.html
{% extends 'crud_app/base.html' %}


{% block content %}

<div class="jumbotron">
  <h1>Welcome to the school detail page</h1>
  <h1>School Details:</h1>

  <h2>Name: {{school.name}}</h2>
  <h2>Princial: {{school.principal}}</h2>
  <h2>Location: {{school.location}}</h2>

  <h3>Students:</h3>
  {% for student in school.student.all %}
  <p>{{student.name}} who is {{student.age}} years old.</p>
  {% endfor %}

  <p><a class="btn btn-warning" href="{% url 'crud_app:update'  school.id %}">Update</a></p>
</div>

<p>
  <a class="btn btn-danger" href="{% url 'crud_app:delete' school.id %}">Delete {{school.name}}</a>
</p>

{% endblock content %}

crud_app/templates/crud_app/school_form.html
{% extends 'crud_app/base.html' %}


{%  block content %}

{% if not form.instance.pk %}
  <h1>Create School</h1>
{% else %}
  <h1>Update School</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" class='btn btn-primary'  value="Submit" name="" id="">
</form>
{% endblock content %}

crud_app/templates/crud_app/school_list.html
{% extends 'crud_app/base.html' %}

{% block content %}

<h1>Names of all the schools</h1>


<div class="jumbotron">
  <ol>
    {% for school in school_list %}
      <h1><li><a href="{% url 'crud_app:detail' school.id %}">{{school.name}}</a></li></h1>
    {% endfor %}
  </ol>

</div>

<a class="btn btn-primary" href="{% url 'crud_app:create' %}">Create New School</a>

{% endblock content %}